### ISSUE TITLE
WITH_FUTURE_DATES = False crashes comparing datetimes

### ISSUE THREAD

**Issue by zackw** [getpelican/pelican#1666]
I tried to set `WITH_FUTURE_DATES = False` for a site where I want to write posts in advance and have them automatically appear (via a cron job) when their date comes around.  This mode appears to have been broken for quite some time:  I get this error message for every single post:

~~~~
ERROR: Could not process [REDACTED]
  | can't compare offset-naive and offset-aware datetimes
  |___
  | Traceback (most recent call last):
  |   File ".../site-packages/pelican/generators.py", line 502, in generate_context
  |     context_sender=self)
  |   File ".../site-packages/pelican/readers.py", line 492, in read_file
  |     context=context)
  |   File ".../site-packages/pelican/contents.py", line 136, in __init__
  |     if hasattr(self, 'date') and self.date > SafeDatetime.now():
  | TypeError: can't compare offset-naive and offset-aware datetimes
~~~~

and the generated site is empty.

This is with Python 2.7, fwiw.

**Comment by ingwinlu** [comment]
https://github.com/getpelican/pelican/issues/1536

**Comment by zackw** [comment]
Hm, so, fixed in the development version?  I'll test that.

**Comment by eflee** [comment]
Where is this. It's broken with WITH_FUTURE_DATES = True with Pelican installed via pip install -e "git+https://github.com/getpelican/pelican.git#egg=pelican"

**Comment by avaris** [comment]
@eflee broken how?

**Comment by russellballestrini** [comment]
This is still an issue for me in pelican 3.5.0.  This issue doesn't occur in pelican 3.4.0.  Here is some proof:

```
pelican --version
3.5.0
```

Same error whether WITH_FUTURE_DATES is True or False:

```
(env)myuser@myhost ~/h/myblog> make html;
find /home/myuser/hg/myblog/output -mindepth 1 -delete
pelican /home/myuser/hg/myblog/content -o /home/myuser/hg/myblog/output -s /home/myuser/hg/myblog/pelicanconf.py 
CRITICAL: can't subtract offset-naive and offset-aware datetimes
Makefile:46: recipe for target '/home/myuser/hg/myblog/output/index.html' failed
make: *** [/home/myuser/hg/myblog/output/index.html] Error 1
```

```
pelican --version
3.4.0
```

```
(env)myuser@myhost ~/h/myblog> make html;
find /home/myuser/hg/myblog/output -mindepth 1 -delete
pelican /home/myuser/hg/myblog/content -o /home/myuser/hg/myblog/output -s /home/myuser/hg/myblog/pelicanconf.py
Done: Processed 32 article(s), 0 draft(s) and 0 page(s) in 0.48 seconds.
Done
```

**Comment by justinmayer** [comment]
@russellballestrini: Perhaps you should try the current `master` branch?

**Comment by russellballestrini** [comment]
@justinmayer ok, will test.

**Comment by russellballestrini** [comment]
install latest master from github:
```
pip install -e "git+https://github.com/getpelican/pelican.git#egg=pelican"
```

check version:
```
pelican --version
3.5.0
```

```
CRITICAL: can't subtract offset-naive and offset-aware datetimes
```

On further investigation I deduced that it is my custom theme that is attempting to use the date object that is causing the exception!

**Comment by russellballestrini** [comment]
Please ignore my comments above, not directly related to this error.  At some point Pelican started using timezone aware datetime objects and my code was trying to perform math on them without timezones.

**Comment by justinmayer** [comment]
This should be addressed in 3.6, [which was just released](http://blog.getpelican.com/pelican-3.6-released.html).

**Comment by mlissner** [comment]
Ran into this error with pelican 3.6.0 and Python 3.4. 

Fixed it by updating my pelicans-plugins repo with:

    git pull --recurse-submodules
    git submodule update --recursive
